apiVersion: v1
kind: Service
metadata:
  name: {{ include "backendchart.fullname" . }}
  labels:
{{ include "backendchart.labels" . | indent 4 }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "backendchart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: medications-provider
spec:
  selector:
    app: medications
    tier: mock-provider
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001