apiVersion: apps/v1
kind: Deployment
metadata:
  name: medications-frontend
spec:
  selector:
    matchLabels:
      app: medications
      tier: medications-frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: medications
        tier: medications-frontend
        track: stable
    spec:
      containers:
      - name: medications-frontend
        image: "int-capi-harbor.cncpl.us/tc-nextgen/medications-frontend:v0.1.0"
        env:
         - name: SERVER_URI
           value: localhost
        ports:
        - containerPort: 8080