apiVersion: v1
kind: Service
metadata:
  name: medications-frontend
spec:
  selector:
    app: medications
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 4200
  type: LoadBalancer