apiVersion: apps/v1
kind: Deployment
metadata:
  name: medications-backend
spec:
  selector:
    matchLabels:
      app: medications
      tier: medications-backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: medications
        tier: medications-backend
        track: stable
    spec:
      containers:
        - name: medications-backend
          image: "int-capi-harbor.cncpl.us/tc-nextgen/medications-api:v0.1.0"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: MOCK_PROVIDER
              value: medications-provider 
            - name: MOCK_PROVIDER_PORT
              value: "8001"
      